import type { Metadata } from "next";
import localFont from "next/font/local";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const verdana = localFont({
  src: "./fonts/verdana.ttf",
  variable: "--font-verdana",
  weight: "400",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--open-sans",
});

export const metadata: Metadata = {
  title: "web Mail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${verdana.variable} ${openSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
